### ISSUE TITLE
Добрый день

### ISSUE THREAD

**Issue by Albertius26** [vitaly-s/robocopy#2]
Здравствуйте. Есть возможность добавить поле папка источник? чтобы не выбирать каждый раз. Также можете добавить график выборочный, для запуска задач robocopy

**Comment by vitaly-s** [comment]
Добрый день.
Попробуйте создать переодическую задачу: "Панель управления"-"Планировщик задач"-"Создать"-"Запланированная задача"-"Скрипт, заданный пользователем". 
В поле "Настройки задачи":"Скрипт, заданный пользователем" задайте: 
`/var/packages/robocopy/target/bin/robocopy.pl [путь к обрабатываемой папке1] [путь к обрабатываемой папке2] ...`

Посмотреть путь к папке можно в свойствах папки, поле "Местоположение". Если путь к папке содержит пробелы, то путь небходимо указывать в кавычках.

Например:
`/var/packages/robocopy/target/bin/robocopy.pl "/volume1/shared/usb Дата" /volume1/shared/test`

Результаты будут отображены в журнале: "Центр журналов"-"Журналы"-"Общие"

**Comment by vitaly-s** [comment]
Hi.
Try creating scheduled task: "Control Panel" - "Task Scheduler" - "Create" - "Scheduled Task" - "User-defined script".
In field "Task settings":"User-defined script" set:
`/var/packages/robocopy/target/bin/robocopy.pl [path to processed folder1] [path to processed folder2] ...`

You can see folder path in folder properties, the "Location" field. If folder path contains spaces, then path must be enclosed in quotation marks.

For example:
`/var/packages/robocopy/target/bin/robocopy.pl "/volume1/shared/usb Date" /volume1/shared/test`

Results may be seen in log: "Log Center" - "Logs" - "General"

**Comment by Albertius26** [comment]
Спасибо тебе, друг. Дай Бог тебе здоровья
