### ISSUE TITLE
No way to declare source directory

### ISSUE THREAD

**Issue by bradvanderwielen** [vitaly-s/robocopy#3]
Please excuse me if I am missing something, but there is no way to declare a source directory, correct?  I have multiple users that want to sort pictures BUT do not want them to mix.  As I understand it currently this tool looks for all files with the declared extension throughout the device.

Is it possible to declare a source directory tree?

Thanks!

**Comment by bradvanderwielen** [comment]
Actually, when you hit run it asks which folder you want to run the tool on.  Nevermind.  Thanks!!!!

**Comment by vitaly-s** [comment]
Hi,
You can run RoboCopy from File Station over context menu
